openapi: 3.0.0
info:
  title: News Portal API
  description: Yangiliklar  uchun Backend API 
  version: 1.0.0

servers:
  - url: http://127.0.0.1:5000
    description: Lokal server
    

paths:
  /auth/login:
    post:
      summary: Kirish , Token olish
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:               
                  type: string
                  example: "admin"
                password:
                  type: string
                  example: "yangi_parolim123"
      responses:
        '200':
          description: Muvaffaqiyatli kirildi (Token qaytdi)

  /categories:
    get:
      summary: Barcha kategoryalarni olish
      responses:
        '200':
          description: Kategoriyalar ro'yxati
    post:
      summary: Yangi kategorya yaratish
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Texnologiya"
                slug:
                  type: string
                  example: "texnologiya"
      responses:
        '201':
          description: Kategory yaratildi


  /posts:
    get:
      summary: Barcha yangiliklarni olish
      responses:
        '200':
          description: Yangiliklar roixati
    post:
      summary: Yangi yangilik qoshish
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Sun'iy intellekt rivojlanishi"
                content:
                  type: string
                  example: "Yangilikning to'liq matni..."
                category_id:
                  type: integer
                  example: 1
      responses:
        '201':
          description: Yangilik yaratildi


  /pages:
    get:
      summary: Barcha sahifani olish
      responses:
        '200':
          description: Sahifa ro'yxati qaytdi
    post:
      summary: Yangi sahifa yaratish
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - slug
              properties:
                title:
                  type: string
                  example: "Biz haqimizda"
                content:
                  type: string
                  example: "Project haqida  ma'lumot..."
                slug:
                  type: string
                  example: "biz haqimizda"
      responses:
        '201':
          description: Sahifa yaratildi
        '400':
          description: Ma'lumotlar  togri emas

  /comments:
    get:
      summary: Barcha izohlarni olish
      responses:
        '200':
          description: Izohlar ro'yxati qaytdi
    post:
      summary: Postga yangi izoh qo'shish
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - post_id
                - text
              properties:
                post_id:
                  type: integer
                  example: 1
                text:
                  type: string
                  example: "Juda ajoyib yangilik bolibdi!"
      responses:
        '201':
          description: Izoh saqlandi
        '400':
          description:  matn yoki post_id notori
        '404':
          description: post topilmadi